name: OpenChatKit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8.0
  - cupy=12.1.0
  - faiss-gpu=1.7.2
  - fastparquet=0.5.0
  - nccl=2.18.3.1
  - pip=23.2
  - pyarrow=12.0.1
  - python=3.10.9
  - python-snappy=0.6.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - snappy=1.1.9
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pip:
      - accelerate==0.21.0
      - boto3
      - datasets==2.13.1
      - loguru==0.6.0
      - netifaces==0.11.0
      - pandas==2.0.3
      - transformers==4.31.0
      - wandb==0.15.5
      - zstandard==0.21.0
      - sentencepiece
